# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='quantita_ko',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ordine',
            name='quantita_ok',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
