# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0002_auto_20151206_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordine',
            old_name='articolo',
            new_name='lavorazione',
        ),
    ]
