# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0003_auto_20151208_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordine',
            old_name='consegna',
            new_name='termine',
        ),
    ]
