# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0004_auto_20151208_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='data_apertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='data_chiusura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
