# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lavorazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True)),
                ('descrizione', models.CharField(max_length=20)),
                ('tempo', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'lavorazioni',
                'verbose_name': 'lavorazione',
                'ordering': ['codice'],
            },
        ),
    ]
