# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0002_auto_20151206_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impianto',
            name='note',
        ),
    ]
