# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0003_remove_impianto_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='impianto',
            name='pannello',
            field=models.GenericIPAddressField(default='0.0.0.1'),
        ),
    ]
