# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0004_impianto_pannello'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impianto',
            old_name='pannello',
            new_name='ip_pannello',
        ),
    ]
