# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operatori', '0004_auto_20151206_1346'),
        ('impianti', '0006_remove_impianto_ip_pannello'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pannello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso', models.BooleanField(default=False)),
                ('allarme', models.BooleanField(default=False)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='impianti.Impianto')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatori.Operatore')),
            ],
            options={
                'verbose_name': 'pannello',
                'verbose_name_plural': 'pannelli',
            },
        ),
    ]
