# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0007_pannello'),
    ]

    operations = [
        migrations.AddField(
            model_name='pannello',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.1'),
        ),
    ]
