# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0008_pannello_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pannello',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.1', null=True),
        ),
    ]
