# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0009_auto_20151206_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pannello',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.1'),
        ),
        migrations.AlterField(
            model_name='pannello',
            name='operatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operatori.Operatore'),
        ),
    ]
