# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0010_auto_20151206_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='pannello',
            name='codice',
            field=models.CharField(default='p', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
