# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0002_auto_20151206_1346'),
        ('impianti', '0011_pannello_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pannello',
            name='ordine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordini.Ordine'),
        ),
    ]
