# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0012_pannello_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pannello',
            name='impianto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impianti.Impianto'),
        ),
    ]
