# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impianti', '0013_auto_20151208_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pannello',
            name='impianto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='impianti.Impianto'),
            preserve_default=False,
        ),
    ]
