# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operatori', '0004_auto_20151206_1346'),
        ('ordini', '0002_auto_20151206_1346'),
        ('impianti', '0006_remove_impianto_ip_pannello'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istante', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(choices=[('PW0', 'Impianto spento'), ('PW1', 'Impianto acceso'), ('AL0', 'Allarme rientrato'), ('AL1', 'Allarme scattato'), ('OP0', 'Operatore disinserito'), ('OP1', 'Operatore inserito')], max_length=3)),
                ('quantita_ok', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('quantita_ko', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impianti.Impianto')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatori.Operatore')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordini.Ordine')),
            ],
            options={
                'verbose_name_plural': 'registrazioni',
                'ordering': ['istante'],
                'verbose_name': 'registrazione',
            },
        ),
    ]
