# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrazione',
            options={'ordering': ['-istante'], 'verbose_name': 'registrazione', 'verbose_name_plural': 'registrazioni'},
        ),
    ]
