# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrazioni', '0002_auto_20151207_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrazione',
            name='evento',
            field=models.CharField(choices=[('ON', 'Impianto spento'), ('OFF', 'Impianto acceso'), ('AL+', 'Allarme scattato'), ('AL-', 'Allarme rientrato'), ('OPI', 'Operatore inserito'), ('OPD', 'Operatore disinserito')], max_length=3),
        ),
    ]
