# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrazioni', '0004_auto_20151208_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrazione',
            name='ordine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordini.Ordine'),
        ),
    ]
