# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordini', '0002_auto_20151206_1346'),
        ('impianti', '0012_pannello_ordine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorita', models.PositiveIntegerField(default=1)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impianti.Impianto')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordini.Ordine')),
            ],
            options={
                'verbose_name': 'scheda',
                'verbose_name_plural': 'schede',
            },
        ),
    ]
