# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheda',
            name='data_fine',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='data_inizio',
            field=models.DateTimeField(),
        ),
    ]
