# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programma', '0002_auto_20151207_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheda',
            name='data_fine',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='data_inizio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
