# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatori', '0002_remove_operatore_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatore',
            name='tessera',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
