# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatori', '0003_operatore_tessera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatore',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
