# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatori', '0004_auto_20151206_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatore',
            name='tipo',
            field=models.CharField(choices=[('O', 'Operaio'), ('A', 'Attrezzista'), ('Q', 'Controllo qualità')], default='O', max_length=1),
        ),
    ]
